[build-system]
requires = [
    "setuptools"
]
build-backend = "setuptools.build_meta"

[project]
name = "pyInegi"
authors = [
    {name = "INEGI", email = "inegi@inegi.org.mx"},
    {name = "Genertalizacion", email = "generalizacion@inegi.org.mx"},
]
readme = "README.md"
requires-python = ">=3.7"
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["version", "description"]

dependencies =  [
    umpy>=2.1.1,
    matplotlib>=3.9.2,
    folium>=0.17.0,
    mapclassify>=2.8.0,
    httpimport>=1.4.0,
    geopandas>=1.0.1,
    requests>=2.32.3,
    shapely>=2.0.6,
    scipy>=1.14.1,
    fiona>=1.10.1,
    euclid3>=0.1,
    rtree
]

[project.optional-dependencies]
test = [
    "black==21.9b0",
    "pre-commit==2.15.0",
    "mypy==0.910",
    "pytest==6.2.5",
    "pytest-cov==3.0.0",
]

deploy = [
    "flit==3.4.0",
]