[build-system]
requires = [
    "setuptools",
    "some_build_toolkit", 
    "wheel"
]
build-backend="setuptools.build_meta"

[setuptools.setup]
script = "pyInegi"
generate-setup-file = false

dependencies = [
    "requests",
    "pandas",
    "numpy",
    "matplotlib",
    "geopandas",
    "folium",
    "mapclassify",
    "shapely",
    "httpimport",
    "scipy"
]

[project]
name = "pyInegi"
dynamic = ["version"]



