[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend="setuptools.build_meta"

[tool.setuptools.setup]
script = "setup.py"
generate-setup-file = false

dependencies = [
    "requests",
    "pandas",
    "numpy",
    "matplotlib",
    "geopandas",
    "folium",
    "mapclassify",
    "shapely",
    "httpimport",
    "scipy"
]

[project]
name="pyInegi"
version="1.0.0"



