[build-system]
requires = [
    "setuptools",
    "wheel"
]
build-backend="setuptools.build_meta"

[project]
name = "pyInegi"
version = "1.0.0"
dependencies = [
    "requests",
    "pandas",
    "numpy",
    "matplotlib",
    "geopandas",
    "folium",
    "mapclassify",
    "shapely",
    "httpimport",
    "scipy",
    "rtree",
]
