[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend="setuptools.buil-meta"
dependencies = [
    "requests",
    "pandas",
    "numpy",
    "matplotlib",
    "geopandas",
    "folium",
    "mapclassify",
    "shapely",
    "httpimport"
]

[project]
name="pyInegi"
version="1.0.0"
autor="INEGI"
fecha="2024"



